# Generated by Django 3.2.4 on 2021-07-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
